version: '3.7'
services:
  database:
    platform: linux/x86_64
    image: mysql:5.7
    container_name: db_set
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=set
      - MYSQL_USER=set
      - MYSQL_PASSWORD=set
      - MYSQL_ROOT_PASSWORD=set
    volumes:
      - my-db:/var/lib/mysql

volumes:
  node_modules: {}
  my-db: 
    driver: local